name: mne_bids
channels:
- defaults
- conda-forge
dependencies:
- python<3.7
- pip=19
- mkl
- numpy
- scipy
- scikit-learn
- matplotlib
- pip:
  - mne
  - mne-bids
  - nibabel
  - nilearn
  - flake8
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-faulthandler
  - check-manifest
  - sphinx
  - pillow
  - numpydoc
  - sphinx_bootstrap_theme
  - sphinx_gallery
